Set up preinstallpecommands

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,35 +53,15 @@ jobs:
     secrets: "inherit"
     with:
       flags: " --exclude-platforms '[\"CentOS-7\",\"CentOS-8\",\"OracleLinux-8\",\"RedHat-7\",\"RedHat-8\",\"OracleLinux-7\",\"Scientific-7\",\"SLES-12\"]'" # Only way for Acceptance CI to run in the absence of vmpooler's VMs
-      installpecommands: >
-        echo "===FailSafe PE Installation, in case the original one fail===" ;
-        PEVERSION='2021.7.8' ;
-        pepasswd="pie$(date +%s )piepiepiepiepiepiepiepiepieP5!" ;
-        version=$(puppet --version) || echo ;
-        version="NOT NEEDED SO ByPassed" ;
-        if  [ -z "$version" ] ; then
-          echo "===Installing Puppet Version Installed=${PEVERSION} my way===" ;
-          apt install -y curl || yum install -y curl ;
-          curl -q "https://raw.githubusercontent.com/sooyean-hoo/pe_curl_requests/feature/SYInstallerEnhance/installer/download_pe_tarball.sh"  > /tmp/download_pe_tarball.sh ;
-          source /tmp/download_pe_tarball.sh  loadlib ;
-          echo -e "srcgitKey='/tmp/key2share'\ndisplay_local_time=true\nadminpasswd=\"$pepasswd\"" > /tmp/installPEConsole.SETVALUES.txt ;
-          touch /tmp/key2share ;
-          installPEConsole =SETVALUES= ;
-          installPEConsole - =SETVALUES==PRECHECK==UNTAR==PRECONFIG=PRECONFIG2=  ;
-          dlPEConsole check ${PEVERSION} ;
-          dlPEConsole show ${PEVERSION} ;
-          installPEConsole ;
-        else
-          echo "===Puppet Version Installed=${version}===" ;
-        fi ;
-      deploy_peversion: '-'
-      prepcommand1: >
+      preinstallpecommands: >
         sshverbose="-vvvvvv" ;         sshverbose="" ;
-        VAGRANTRUN="Y";
-        echo "===Puppet Version Installed=$(puppet --version)===" || echo ;
+        VAGRANTRUN="Y" ;
+        echo ;
         ( sudo apt install -y curl || sudo yum install -y curl || apt install -y curl || yum install -y curl ) &&
         curl -q "https://raw.githubusercontent.com/sooyean-hoo/pe_curl_requests/feature/SYInstallerEnhance/installer/download_pe_tarball.sh"  > /tmp/download_pe_tarball.sh  ;
         source /tmp/download_pe_tarball.sh  loadlib  ;
+        echo ;
+        echoMsg '!!' "Preparing the System for Vagrant or Docker, depends on situation" ;
         pkgs='git git-core zlib* zlib*-dev g++     patch                    libyaml* libffi-dev       libffi*dev          make bzip2 autoconf automake libtool bison curl cmake ruby-dev wget sshpass';
         snappkgs='snapd' ;
         vagrantpkgs='vagrant virtualbox virt-manager build-essential ruby-full ruby-all-dev libvirt-dev ' ;
@@ -123,12 +103,21 @@ jobs:
         echo -e '\n  - name: servicenow_instance\n    targets:\n      - uri: localhost\n        vars:\n          roles:\n            - servicenow_instance' '>> inventory.yaml' > /dev/null &&
         cat ./inventory.yaml && 
         cp -f ./inventory.yaml ./spec/fixtures/litmus_inventory.yaml ;
+        echoMsg '!!' "Provision Starts" ;
         bundle install ;
         bundle exec 'rake --tasks' ;
         bundle install ;
-        ssh-keygen -t ed25519 -f /tmp/myownkey      -P '' ; grep -H -n -v -E 'AALINEAANUMBER'  /tmp/myownkey* ;
         export VAGRANT_PASSWORD="pie$(date +%s )piepiepiepiepiepiepiepiepieP5!"  ;
+        echo ;
+        echo ;
+        echo ;
+        echo ;
         bundle exec 'rake acceptance:provision_vms ' ;
+        echo ;
+        echo ;
+        echo ;
+        echo ;
+        echoMsg '!!' "Provision Adjustment and Checks Starts" ;
         ssh-keygen -R localhost ; 
         grep -H -n -v -E 'AALINEAANUMBER'  ./inventory.yaml ./spec/fixtures/litmus_inventory.yaml ;
         provisioner=$( cat ./spec/fixtures/litmus_inventory.yaml | yq -e '.groups[]|select( .name == "ssh_nodes" )|.targets.[0].facts.provisioner' ) ;
@@ -139,6 +128,7 @@ jobs:
           sshpass -p root ssh -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 ${sshverbose} -p52599 -l root 127.0.0.1 date  ||  echo "FAIL: ssh with default passwd based on generate inv..."  ;
         elif [ "vagrant" =  "$provisioner" ] ; then
           echo "=======VAGRANT RUN=======" ;
+          ssh-keygen -t ed25519 -f /tmp/myownkey      -P '' ; grep -H -n -v -E 'AALINEAANUMBER'  /tmp/myownkey* ;
           echo "===Proposed Changes===" ;
           cat ./spec/fixtures/litmus_inventory.yaml |  yq  '.groups[3].targets[0].config.ssh.private-key="/tmp/myownkey"' | tee ./spec/fixtures/litmus_inventory.yaml.proposed | grep -H -n -v -E 'AALINEAANUMBER' ;
           echo "=============================================================" ;
@@ -168,9 +158,33 @@ jobs:
         else
           echo "=======SKIPPED COS Unsupported provisioner: $provisioner =======" ;
         fi ;
+      deploy_peversion: '2021.7.8'
+      installpecommands: >
+        echo "===FailSafe PE Installation, in case the original one fail===" ;
+        PEVERSION='2021.7.8' ;
+        pepasswd="pie$(date +%s )piepiepiepiepiepiepiepiepieP5!" ;
+        version=$(puppet --version) || echo ;
+        version="NOT NEEDED SO ByPassed" ;
+        if  [ -z "$version" ] ; then
+          echo "===Installing Puppet Version Installed=${PEVERSION} my way===" ;
+          apt install -y curl || yum install -y curl ;
+          curl -q "https://raw.githubusercontent.com/sooyean-hoo/pe_curl_requests/feature/SYInstallerEnhance/installer/download_pe_tarball.sh"  > /tmp/download_pe_tarball.sh ;
+          source /tmp/download_pe_tarball.sh  loadlib ;
+          echo -e "srcgitKey='/tmp/key2share'\ndisplay_local_time=true\nadminpasswd=\"$pepasswd\"" > /tmp/installPEConsole.SETVALUES.txt ;
+          touch /tmp/key2share ;
+          installPEConsole =SETVALUES= ;
+          installPEConsole - =SETVALUES==PRECHECK==UNTAR==PRECONFIG=PRECONFIG2=  ;
+          dlPEConsole check ${PEVERSION} ;
+          dlPEConsole show ${PEVERSION} ;
+          installPEConsole ;
+        else
+          echo "===Puppet Version Installed=${version}===" ;
+        fi ;
+      prepcommand1: >
+        echo "===Puppet Version Installed=$(puppet --version)===" || echo ;
       command: >
         source /tmp/download_pe_tarball.sh  loadlib  ;
-        echoMsg == "Running the actual Acceptance Tests" || echo "============================Running the actual Acceptance Tests============================== " ;
+        echoMsg '!!' "Running the actual Acceptance Tests" || echo "============================Running the actual Acceptance Tests============================== " ;
         bundle install ;
         bundle exec 'rake acceptance:setup_pe_p2 acceptance:setup_servicenow_instance ' ;
         echo "============================After Update from setup_servicenow_instance " ;
