Testing new Vagrant access

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -152,14 +152,19 @@ jobs:
         ssh-keygen -R localhost ; 
         grep -H -n -v -E 'AALINEAANUMBER'  ./inventory.yaml ./spec/fixtures/litmus_inventory.yaml ;
         echo "===Proposed Changes===" ;
-        cat ./spec/fixtures/litmus_inventory.yaml |  yq  '.groups[3].targets[0].config.ssh.private-key="/tmp/myownkey"' | grep -H -n -v -E 'AALINEAANUMBER' ;
+        cat ./spec/fixtures/litmus_inventory.yaml |  yq  '.groups[3].targets[0].config.ssh.private-key="/tmp/myownkey"' | tee  ./spec/fixtures/litmus_inventory.yaml.proposed | grep -H -n -v -E 'AALINEAANUMBER' ;
         echo "==============" ;
         ls -l /home/runner/.vagrant.d/insecure_private_keys/vagrant.key.ed25519 ;
         ls -l /home/runner/.vagrant.d/insecure_private_keys/ ;
         pwd ; ls -l ; ls -l /home/runner/.vagrant.d/ ; vagrant global-status ;
+        OLDCWD=$(pwd) ;
         echo "=====vagrant ssh default===========" ;
         pushd `pwd` ; cd spec/fixtures/.vagrant/generic-ubuntu2204-0 ;pwd ;
-        vagrant ssh default  --command "ls -l /home/vagrant/.ssh" || echo "FAIL: vagrant ssh default.....date" ;
+        vagrant ssh default  --command "cat /home/vagrant/.ssh/authorized_keys" || echo "FAIL: vagrant ssh default.....date" ;
+        echo "=============Updating keys of vagrant ssh default===========" ;
+        cat /tmp/myownkey.pub | vagrant ssh default  --command "cat >> /home/vagrant/.ssh/authorized_keys" || echo "FAIL: vagrant ssh default.....date" ;
+        vagrant ssh default  --command "cat /home/vagrant/.ssh/authorized_keys |  grep -H -n -v -E 'AALINEAANUMBER' " || echo "FAIL: vagrant ssh default.....date" ;
+        cat  ${OLDCWD}/spec/fixtures/litmus_inventory.yaml.proposed >  ${OLDCWD}/spec/fixtures/litmus_inventory.yaml ;
         echo "==============" ;
         vagrant ssh default  --command "grep -H -n -v -E 'AALINEAANUMBER'  /home/vagrant/.ssh/*" || echo "FAIL: vagrant ssh default....." ; 
         popd ;
