more vagrant tweaking
Signed-off-by: Hoo Sooyean (何書淵) <Sooyean.hoo@perforce.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,7 +106,7 @@ jobs:
         ( sudo apt install -y curl || sudo yum install -y curl || apt install -y curl || yum install -y curl ) &&
         curl -q "https://raw.githubusercontent.com/sooyean-hoo/pe_curl_requests/feature/SYInstallerEnhance/installer/download_pe_tarball.sh"  > /tmp/download_pe_tarball.sh  ;
         source /tmp/download_pe_tarball.sh  loadlib  ;
-        pkgs='git git-core zlib* zlib*-dev g++     patch                    libyaml* libffi-dev       libffi*dev          make bzip2 autoconf automake libtool bison curl cmake ruby-dev wget ' ;
+        pkgs='git git-core zlib* zlib*-dev g++     patch                    libyaml* libffi-dev       libffi*dev          make bzip2 autoconf automake libtool bison curl cmake ruby-dev wget sshpass' ;
         vagrantpkgs='vagrant virtualbox virt-manager build-essential ruby-full ruby-all-dev libvirt-dev ' ;
         echo "=====Pkgs=${pkgs}=============" ;
         installPkg $pkgs ;
@@ -135,7 +135,7 @@ jobs:
         gem install --force  strscan --version 3.1.0 ;
         gem install --force  rake -v 13.2.1 ;
         gem install --force  CFPropertyList  -v 2.3.6  ;
-        mkdir -p /home/runner/.ssh ; touch /home/runner/.ssh/known_hosts ;
+        mkdir -p /home/runner/.ssh ; touch /home/runner/.ssh/known_hosts ; touch  ~/.ssh/known_hosts ; ssh-keygen -R localhost ; 
         echo -e '\n  - name: master\n    targets:\n      - uri: localhost\n        vars:\n          role: master'   >> inventory.yaml ; 
         echo -e '\n  - name: servicenow_instance\n    targets:\n      - uri: localhost\n        vars:\n          role: servicenow_instance'  >> inventory.yaml &&
         cat ./inventory.yaml && 
@@ -143,12 +143,23 @@ jobs:
         bundle install ;
         bundle exec 'rake --tasks' ;
         bundle install ;
+        ssh-keygen -t ed25519 -f /tmp/myownkey      -P '' ; grep -H -n -v -E 'AALINEAANUMBER'  /tmp/myownkey* ;
+        export VAGRANT_PASSWORD="pie$(date +%s )piepiepiepiepiepiepiepiepieP5!"  ;
         bundle exec 'rake acceptance:provision_vms ' ;
+        ssh-keygen -R localhost ; 
         grep -H -n -v -E 'AALINEAANUMBER'  ./inventory.yaml ./spec/fixtures/litmus_inventory.yaml ;
         ls -l /home/runner/.vagrant.d/insecure_private_keys/vagrant.key.ed25519 ;
         ls -l /home/runner/.vagrant.d/insecure_private_keys/ ;
         pwd ; ls -l ; ls -l /home/runner/.vagrant.d/ ; vagrant global-status ;
-        ssh  -i /home/runner/.vagrant.d/insecure_private_keys/vagrant.key.ed25519 -vvvvvv -p2222 127.0.0.1 date  || echo ;
+        echo "=====vagrant ssh default===========" ;
+        pushd `pwd` ; cd spec/fixtures/.vagrant/generic-ubuntu2204-0 ;pwd ;
+        vagrant ssh default  --command "ls -l /home/vagrant/.ssh" || echo "FAIL: vagrant ssh default.....date" ; 
+        echo "==============" ;
+        vagrant ssh default  --command "grep -H -n -v -E 'AALINEAANUMBER'  /home/vagrant/.ssh/*" || echo "FAIL: vagrant ssh default....." ; 
+        popd ;
+        echo "===== ssh ===========" ;
+        ssh  -i /home/runner/.vagrant.d/insecure_private_keys/vagrant.key.ed25519 -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 -vvvvvv -p2222 -l vagrant 127.0.0.1 date  ||  echo "FAIL: ssh ..."  ;
+        echo "==========================" ;
         bundle install ;
         bundle exec 'rake acceptance:setup_pe_p2 acceptance:setup_servicenow_instance acceptance:install_module' ;
         echo bundle exec 'acceptance:provision_vms acceptance:setup_pe_p2 acceptance:setup_servicenow_instance acceptance:install_module' ;
