Switch to a new design, and update the scripts
Signed-off-by: Hoo Sooyean (何書淵) <Sooyean.hoo@perforce.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,6 +23,28 @@ jobs:
     uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
     secrets: "inherit"
 
+# Firstly, I am not the original author of the Acceptance Tests. It took me 
+# weeks to figure out what is the design and the original author's intentions. 
+# Have fun using 'git blame'.
+
+# The original Acceptance Test is using VMPooler... so it run the VMPooler to 
+# get a machine via SSH... as master. Inside the master, you run a mockup 
+# ServiceNow in a docker to test against. All acceptance tests are to be run on 
+# the master. VMPooler is now deprecated. Hence I am using vagrant to replace 
+# the VMPooler VM, using docker as a replacement has proven to be not working, 
+# as it is hard to have a docker within a docker container. In fact, it is 
+# impossible.
+
+# It is also silly to try to change the test to work with 2 containers: too much
+# changes. The original author use litmus to only provision 1 VM: the master. 
+# The rest of the provision, the servicenow, it did it not via Litmus, but it 
+# still want to use it to manage and access the docker. This is where it is 
+# confusing. There is a 'servicenow_instance' in 
+# spec/support/acceptance/helpers.rb, magically created. It is not mentioned at 
+# all in provision.yaml. It is not created by the litmus, but a script. I would 
+# called it, as a way to hack the litmus. Hence it is as good as how litmus stay
+# constant. If there is any future changes to how litmus ingest the inventory. 
+# It may just fail. Good LUCK.
 
 
 
@@ -35,7 +57,8 @@ jobs:
         echo "===FailSafe PE Installation, in case the original one fail===" ;
         PEVERSION='2021.7.8' ;
         pepasswd="pie$(date +%s )piepiepiepiepiepiepiepiepieP5!" ;
-        version=$(puppet --version) ;
+        version=$(puppet --version) || echo ;
+        version="NOT NEEDED SO ByPassed" ;
         if  [ -z "$version" ] ; then
           echo "===Installing Puppet Version Installed=${PEVERSION} my way===" ;
           apt install -y curl || yum install -y curl ;
@@ -51,10 +74,11 @@ jobs:
         else
           echo "===Puppet Version Installed=${version}===" ;
         fi ;
-      deploy_peversion: '2021.7.8'
-      command: >
-        VAGRANTRUN="";
-        echo "===Puppet Version Installed=$(puppet --version)===" ;
+      deploy_peversion: '-'
+      prepcommand1: >
+        sshverbose="-vvvvvv" ;         sshverbose="" ;
+        VAGRANTRUN="Y";
+        echo "===Puppet Version Installed=$(puppet --version)===" || echo ;
         ( sudo apt install -y curl || sudo yum install -y curl || apt install -y curl || yum install -y curl ) &&
         curl -q "https://raw.githubusercontent.com/sooyean-hoo/pe_curl_requests/feature/SYInstallerEnhance/installer/download_pe_tarball.sh"  > /tmp/download_pe_tarball.sh  ;
         source /tmp/download_pe_tarball.sh  loadlib  ;
@@ -95,7 +119,7 @@ jobs:
           gem install --force  CFPropertyList  -v 2.3.6  ;
         fi ;
         mkdir -p /home/runner/.ssh ; touch /home/runner/.ssh/known_hosts ; touch  ~/.ssh/known_hosts ;  
-        echo -e '\n  - name: master\n    targets:\n      - uri: localhost\n        vars:\n          roles:\n            - master'   >> inventory.yaml ; 
+        echo -e '\n  - name: master\n    targets:\n      - uri: localhost\n        vars:\n          roles:\n            - master   >> inventory.yaml' > /dev/null  ; 
         echo -e '\n  - name: servicenow_instance\n    targets:\n      - uri: localhost\n        vars:\n          roles:\n            - servicenow_instance' '>> inventory.yaml' > /dev/null &&
         cat ./inventory.yaml && 
         cp -f ./inventory.yaml ./spec/fixtures/litmus_inventory.yaml ;
@@ -112,16 +136,18 @@ jobs:
           echo "=======DOCKER RUN=======" ;
           docker ps -a ;
           echo "===== ssh with default passwd based on generate inv ===========" ;
-          sshpass -p root ssh -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 -vvvvvv -p52599 -l root 127.0.0.1 date  ||  echo "FAIL: ssh with default passwd based on generate inv..."  ;
+          sshpass -p root ssh -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 ${sshverbose} -p52599 -l root 127.0.0.1 date  ||  echo "FAIL: ssh with default passwd based on generate inv..."  ;
         elif [ "vagrant" =  "$provisioner" ] ; then
           echo "=======VAGRANT RUN=======" ;
           echo "===Proposed Changes===" ;
-          cat ./spec/fixtures/litmus_inventory.yaml |  yq  '.groups[3].targets[0].config.ssh.private-key="/tmp/myownkey"' | tee  ./spec/fixtures/litmus_inventory.yaml.proposed | grep -H -n -v -E 'AALINEAANUMBER' ;
-          echo "==============" ;
+          cat ./spec/fixtures/litmus_inventory.yaml |  yq  '.groups[3].targets[0].config.ssh.private-key="/tmp/myownkey"' | tee ./spec/fixtures/litmus_inventory.yaml.proposed | grep -H -n -v -E 'AALINEAANUMBER' ;
+          echo "=============================================================" ;
           ls -l /home/runner/.vagrant.d/insecure_private_keys/vagrant.key.ed25519 ;
           ls -l /home/runner/.vagrant.d/insecure_private_keys/ ;
           pwd ; ls -l ; ls -l /home/runner/.vagrant.d/ ; vagrant global-status ;
           OLDCWD=$(pwd) ;
+          echo "===== ssh with vagrantkey ===========" ;
+          ssh  -i /home/runner/.vagrant.d/insecure_private_keys/vagrant.key.ed25519 -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 -vvvvvv -p2222 -l vagrant 127.0.0.1 date  ||  echo "FAIL: ssh with vagrantkey..."  ;
           echo "=====vagrant ssh default===========" ;
           pushd `pwd` ; cd spec/fixtures/.vagrant/generic-ubuntu2204-0 ;pwd ;
           vagrant ssh default  --command "cat /home/vagrant/.ssh/authorized_keys" || echo "FAIL: vagrant ssh default.....date" ;
@@ -134,16 +160,17 @@ jobs:
           echo "==============" ;
           vagrant ssh default  --command "grep -H -n -v -E 'AALINEAANUMBER'  /home/vagrant/.ssh/*" || echo "FAIL: vagrant ssh default....." ; 
           popd ;
-          echo "===== ssh with vagrantkey ===========" ;
-          ssh  -i /home/runner/.vagrant.d/insecure_private_keys/vagrant.key.ed25519 -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 -vvvvvv -p2222 -l vagrant 127.0.0.1 date  ||  echo "FAIL: ssh with vagrantkey..."  ;
           echo "===== ssh with /tmp/myownkey ===========" ;
-          ssh  -i /tmp/myownkey -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 -vvvvvv -p2222 -l vagrant 127.0.0.1 date  ||  echo "FAIL: ssh with /tmp/myownkey..."  ;
+          ssh  -i /tmp/myownkey -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 ${sshverbose} -p2222 -l vagrant 127.0.0.1 date  ||  echo "FAIL: ssh with /tmp/myownkey..."  ;
           echo "======ssh puppet install====================" ;
-          ssh  -i /tmp/myownkey -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 -vvvvvv -p2222 -l vagrant 127.0.0.1 "sudo apt install -y puppet"  ||  echo "FAIL: ssh puppet install..."  ;
+          ssh  -i /tmp/myownkey -A -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oTCPKeepAlive=yes -oServerAliveInterval=10 ${sshverbose} -p2222 -l vagrant 127.0.0.1 "sudo apt install -y puppet"  ||  echo "FAIL: ssh puppet install..."  ;
           echo "==========================" ;
         else
           echo "=======SKIPPED COS Unsupported provisioner: $provisioner =======" ;
         fi ;
+      command: >
+        source /tmp/download_pe_tarball.sh  loadlib  ;
+        echoMsg == "Running the actual Acceptance Tests" || echo "============================Running the actual Acceptance Tests============================== " ;
         bundle install ;
         bundle exec 'rake acceptance:setup_pe_p2 acceptance:setup_servicenow_instance ' ;
         echo "============================After Update from setup_servicenow_instance " ;
